server:
  port: 8081
  address: 0.0.0.0
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/serve_auth_db?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: serve_user
    password: serve_pass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  banner:
    charset: UTF-8

logging:
  charset:
    console: UTF-8

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

service:
  team:
    url: ${TEAM_SERVICE_URL:http://localhost:8082}
