apiVersion: apps/v1
kind: Deployment
metadata:
  name: serve-core
  namespace: serve
  labels:
    app: serve-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serve-core
  template:
    metadata:
      labels:
        app: serve-core
    spec:
      containers:
        - name: serve-core
          image: 787858640598.dkr.ecr.ap-northeast-2.amazonaws.com/serve-core:latest
          ports:
            - containerPort: 8083
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: serve-secrets
                  key: DB_HOST
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mariadb://$(DB_HOST):3306/serve_core_db?allowPublicKeyRetrieval=true&useSSL=true&trustServerCertificate=true
&characterEncoding=UTF-8&serverTimezone=Asia/Seoul"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: serve-secrets
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: serve-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: serve-secrets
                  key: JWT_SECRET
            - name: TEAM_SERVICE_URL
              value: "http://serve-team-svc.serve.svc.cluster.local:8082"
            - name: AUTH_SERVICE_URL
              value: "http://serve-auth-svc.serve.svc.cluster.local:8081"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 30
